### ISSUE TITLE
Swedish locale is missing

### ISSUE THREAD

**Issue by hwsoderlund** [CircleCI-Public/cimg-postgres#17]
We are using the circle postgres 9.6 image to execute tests against a real database. We have been using the image `circleci/postgres:9.6-alpine-ram` without issues. Now when I try switching to `cimg/postgres:9.6-postgis` I get an error message about missing locale:

```
ERROR:  invalid locale name: "sv_SE.UTF-8"
```

I tried getting around this by putting `locale-gen sv_SE.UTF-8` in the startup command for the postgres image, but to no success. I am unable to get it to generate the locale _and_ start postgres. 

```yaml
docker:
  - image: cimg/go:1.17
  - image: cimg/postgres:9.6-postgis
    command: locale-gen sv_SE.UTF-8
    environment:
        POSTGRES_USER: xxx
        POSTGRES_DB: xxx
```

I also gave it a go using the postgres 13.4 image, but the locale is missing there too. Is this a mistake, or a deliberate omission?

**Comment by felicianotech** [comment]
I noticed your previous legacy image usage was an Alpine-based image. The next-gen images are Ubuntu only. I wonder if that has something to do with this issue.

Let's find out.

The tags `cimg/postgres:13.4` and `cimg/postgres:9.6.23` have been updated with all of the config options that the official Debian package uses, including some "locale" changed. Do you mind verifying that your issue is resolved if you can use one of those two images?

If we have to manually start including various locales that are out there, I don't think that's something we'd want to do with this image. I don't think the legacy image did that though so I'm hoping this update ends up working for you.

**Comment by hwsoderlund** [comment]
Tried `cimg/postgres:9.6.23` and it doesn't even want to start up:

![2021-11-16_11-02-22](https://user-images.githubusercontent.com/3725915/141964747-560fe5fb-46ec-491f-a53b-c9deba4c1d40.png)

```yaml
docker:
  - image: cimg/go:1.17
  - image: cimg/postgres:9.6.23
    environment:
      POSTGRES_USER: xxx
      POSTGRES_DB: xxx

```
